export const APP_WRITE_ID = '663359a1002cdee6792f'
export const DB_ID = 'crn-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID= 'storage'
